### ISSUE TITLE
some files could be renamed to be effective and/or more standard

### ISSUE THREAD

**Issue by ali0une** [TheBlewish/Web-LLM-Assistant-Llamacpp-Ollama#7]
Hi there!

i think these files could be renamed to be effective and/or more standard :
gitignore -> .gitignore
README.MD -> README.md
Requirements.txt -> requirements.txt

**Comment by TheBlewish** [comment]
Thanks for your input! I just fixed that along with making a big update that makes the program usable with both Llama.cpp and Ollama!
